eks_name             = "eks"
eks_version          = "1.23"
eks_endpoint         = false
public_access        = true
cluster_name         = "eks"
node_group_name      = "node_group"
desired_size         = 2
max_size             = 4
min_size             = 2
ami_type             = "AL2_x86_64"
capacity_type        = "ON_DEMAND"
disk_size            = 20
force_update_version = false
instance_types       = ["t3.small"]
inbound_from_port    = [22, 80]
inbound_to_port      = [22, 80]
inbound_protocol     = "tcp"
inbound_blocks       = ["0.0.0.0/0"]
outbound_from_port   = [0]
outbound_to_port     = [0]
outbound_protocol    = "-1"
outbound_blocks      = ["0.0.0.0/0"]