variable "eks_name" {}
variable "eks_version" {}
variable "eks_endpoint" {}
variable "public_access" {}
variable "cluster_name" {}
variable "node_group_name" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "ami_type" {}
variable "capacity_type" {}
variable "disk_size" {}
variable "force_update_version" {}
variable "instance_types" {}
variable "inbound_from_port" {}
variable "inbound_to_port" {}
variable "inbound_protocol" {}
variable "inbound_blocks" {}
variable "outbound_from_port" {}
variable "outbound_to_port" {}
variable "outbound_protocol" {}
variable "outbound_blocks" {}
variable "created_by" {}
variable "url" {}
variable "security_group_tags" {}