variable "eks_name" {}
variable "eks_version" {}
variable "eks_endpoint" {}
variable "public_access" {}
variable "cluster_name" {}
variable "node_group_name" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "ami_type" {}
variable "capacity_type" {}
variable "disk_size" {}
variable "force_update_version" {}
variable "instance_types" {}